### ISSUE TITLE
Test.py output "ImportError: dynamic module does not define init function (initlibsbml)"

### ISSUE THREAD

**Issue by moriyas1984** [libsbmlsim/libsbmlsim#7]
I installed libsbml and this library to try the sbml simulator from the binary distribution (http://fun.bio.keio.ac.jp/software/libsbmlsim/downloads/libsbmlsim_1.4.0_amd64.deb) but encountered the error in this title when I executed `python2 /usr/share/libsbmlsim/python/Test.py`.

My condition is as follows:
CPU: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
OS: NAME="Ubuntu"
    VERSION="16.04.4 LTS (Xenial Xerus)"

* I downloaded and installed libsbmlsim.
    ```
    $ curl http://fun.bio.keio.ac.jp/software/libsbmlsim/downloads/libsbmlsim_1.4.0_amd64.deb -o libsbmlsim_1.4.0_amd64.deb
    $ sudo dpkg -i libsbmlsim_1.4.0_amd64.deb
    ```
* I downloaded and installed libsbml.
    ```
    $ curl -L https://sourceforge.net/projects/sbml/files/libsbml/5.16.0/stable/Linux/64-bit/libSBML-5.16.0-Linux-x64.deb/download -o libSBML-5.16.0-Linux-x64.deb
    $ sudo dpkg -i libSBML-5.16.0-Linux-x64.deb
    ```
* Because libsbml installed in /usr/lib64, I added the directory to /etc/ld.so.conf.
    ```
    $ cat /etc/ld.so.conf.d/libsbml.conf
    /usr/lib64
    ```
* I executed Test.py and get the error in the title.
    ```
    $ python2 Test.py
    Traceback (most recent call last):
      File "Test.py", line 15, in <module>
        from libsbmlsim import *
    ImportError: dynamic module does not define init function (initlibsbmlsim
    ```

I hope you let me know what I have to do.

**Comment by moriyas1984** [comment]
Additionally, I have checked if libsbml normally work in my environment.

```bash
$ python

Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from libsbml import *
>>> document = SBMLDocument(3, 1)
>>> print(writeSBMLToString(document))
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level3/version1/core" level="3" version="1">
  <model/>
</sbml>

>>>
```

But libsbmlsim does not work...
```bash
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from libsbmlsim import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initlibsbmlsim)
>>>
```
